// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edknrehmzdfwyvchoqop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVka25yZWhtemRmd3l2Y2hvcW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MTA5NzgsImV4cCI6MjA1NTE4Njk3OH0.Eh8zlm_7bjP1NOR1vNaQaedQx3P6nADoOe0Y-S40oIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);